### ISSUE TITLE
Add a readme file

### ISSUE THREAD

**Issue by DonnescoPablo** [master-csmi/Project-management-SCRUM#1]
Add a readme file to describe the project and mention the collaborators.

**Comment by Hassan-Ballout21** [comment]
> Add a readme file to describe the project and mention the collaborators.

Yes you can add the first version. @EarltShirt

**Comment by Hassan-Ballout21** [comment]
Done !!

**Comment by ArielDeVora** [comment]
First version added, look at the different parts and feel free to modify them.
